### ISSUE TITLE
Export of ambiguous function `shape`

### ISSUE THREAD

**Issue by JakobAsslaender** [JuliaImageRecon/LinearOperatorCollection.jl#3]
Hi!

the function `shape` is already exported by `Distributions.jl`, potentially breaking the code in `MRIOperators.jl`, which loads both. 

```
julia> using MRIOperators
WARNING: both Distributions and LinearOperatorCollection export "shape"; uses of it in module MRIOperators must be qualified
```

Would it be possible to use a more descriptive function name instead?

**Comment by tknopp** [comment]
Good point but actually this has two aspects:
* is shape a good descriptive name for the operation?
* should we export it?

Some background. When we have operators we always have the issue that they might be considered as matrices, in which case the underlying (e.g. spatiotemporal) dimensions are dropped on purpose. This is the interface a LinearOperator acts on. And its `size` thus has a clear meaning. Thus we need a different name for this and used shape for it, which is a different  name for `size` in the Python world and thus well established. Until now this concept worked out quite well and is e.g. used also in the Toeplitz operators over at NFFT.jl

So in that sense I think that the answer to
```
Would it be possible to use a more descriptive function name instead?
```
is actually yes. It's very descriptive and changing it here would mean changing it in various packages.

However, regarding the export we might indeed want to remove that. Need to look a little bit where this is used.

@nHackel

**Comment by tknopp** [comment]
Ok, the culprit is actually in LinearOperators itself:
https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/blob/f39deaad34df247c9a16bc8a611b5ed1f4d58d90/src/abstract.jl#L16

I think it makes sense to open an issue at LinearOperators.jl. Our quick fix can only be to just import Distributions in MRIOperators.jl. The alternative is to not reexport LinearOperators in LinearOperatorCollection but at the moment I cannot foresee the consequences of that.

**Comment by JeffFessler** [comment]
> I think it makes sense to open an issue at LinearOperators.jl

i agree.  it seems silly that they export a redundant/duplicate name for `size`.
all the more reason to switch to LinearMaps :)

**Comment by JakobAsslaender** [comment]
I submitted a PR in LinearOperators.jl. Let's see what they say... 

I have no objections against switching to LinearMaps – someone just has to do the work ;).

**Comment by tknopp** [comment]
Maybe a misunderstand LinearMaps but it seems to be much harder to define type base operators, no? In the end this the most important thing that counts for us. We need operators to have unique types on which we can dispatch. This is so damn powerful that it allows us for instance to use the Toeplitz trick in case the operator is NFFT based. All this breaks down if operators have the same type.

**Comment by JeffFessler** [comment]
> All this breaks down if operators have the same type

Oh that's interesting.   I didn't realize that this feature was one of the drivers.

I developed `LinearMapsAA` because I wanted maps that are a subtype of `AbstractMatrix` so that I could develop/debug general optimization methods using small test cases with a `Matrix` and then later plug in any `AbstractMatrix` and have it just work.  I generally don't want the optimizers to know anything about the internals of the maps, or anything about the internals of the data either.  But I haven't implemented the Toeplitz approach (in Julia) so I'd have to think more about that.  Sorry for the detour BTW, and thanks for the insight!

**Comment by JakobAsslaender** [comment]
Fixed by https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/pull/297
